backend/recipes/views.py
import re
import flask
from flask import Blueprint, flash, redirect, render_template, request, url_for

import backend.recipes.queries as ingr_queries
from backend.ingredients.queries import *
from backend.recipes.forms import RegisterRecipeForm
from backend.recipes.queries import *

recipes = Blueprint('recipes', __name__, template_folder='templates')


@recipes.route('/oppskrifter')
def oppskrifter():
    recipes = fetch_all_recipes_to_group(flask.session.get('group_to_use'))

    return render_template('oppskrifter.html', recipes=recipes)


@recipes.route('/oppskrift/<recipe_id>', methods=["GET", "POST"])
def oppskrift(recipe_id: int):
    rec = fetch_recipe_where_recipeId_equals(recipe_id)
    group = flask.session.get('group_to_use')
    group_ingredients = fetch_all_ingredients_where_usergroup_equals(group)

    ingredients = fetch_all_ingredients_where_recipeID_equals(recipe_id, group)
    ingredientInRecipe = []
    ingredientsInStock = []

    for item in ingredients:
        ingredientInRecipe.append(item.ingredientName)

    for item in group_ingredients:
        if item[0].ingredientName not in ingredientInRecipe:
            ingredientsInStock.append(item)
    return render_template('oppskrift.html', rec=rec, ingredients=ingredients, id=recipe_id,
                           ingredientsInStock=ingredientsInStock)


@recipes.route('/oppskrift/<recipe_id>/<ingrediens_id>/delete', methods=["GET", "POST"])
def removeFromRecipeHasIngrediens(recipe_id: int, ingrediens_id: int):
    remove_from_recipe_has_ingredient(recipe_id, ingrediens_id)

    return redirect('/oppskrift/' + str(recipe_id))


@recipes.route('/oppskrift/<recipe_id>/<ingrediens_id>/<value>/update', methods=["GET", "POST"])
def updateRecipeHasIngrediens(recipe_id: int, ingrediens_id: int, value: int):
    editIngredientInRecipe(recipe_id, ingrediens_id, value)

    return redirect('/oppskrift/' + str(recipe_id))


@recipes.route('/oppskrift/<recipe_id>/<ingrediens_id>/<quantity>/add', methods=["GET", "POST"])
def addIngredientToRecipe(recipe_id: int, ingrediens_id: int, quantity: int):
    ingr_queries.insert_to_recipe_has_ingredient(recipe_id, ingrediens_id, quantity)

    return redirect('/oppskrift/' + str(recipe_id))


@recipes.route('/legg-til-rett', methods=["GET", "POST"])
def legg_til_rett():
    group_id = flask.session.get('group_to_use')
    group_ingredients = fetch_all_ingredients_where_usergroup_equals(group_id)
    form = RegisterRecipeForm(request.form)
    if request.method == 'POST' and form.validate():
        # dishId = form.dish.data
        dish = form.dish.data
        short_desc = form.short_desc.data
        long_desc = form.long_desc.data
        ingredienser = form.ingredienser.data

        # Legger til recipe i tabellen

        if fetch_recipeID_where_name_and_groupID_equals(dish, group_id) is None:
            ingr_queries.insert_to_recipe(dish, short_desc, long_desc, 'IMAGE OF DISH', group_id)

            # Henter info fra hidden field, og gjør mening ut av denne(For å få en dynamisk field)
            lst = re.sub("-.*?-", ":o:", ingredienser)

            lst = lst.split(":o:")

            ingrediensLst = []
            for i in lst:
                if i != '':
                    item = i.split(",")
                    if item[1] != '':
                        ingrediensLst.append(item)

            # Kobler ingrediens opp mot recipe
            recipeID = fetch_recipeID_where_name_equals(dish)
            for k in ingrediensLst:
                ingredId = fetch_ingredients_from_all_usergroups_where_name_is(k[0])
                ingr_queries.insert_to_recipe_has_ingredient(str(recipeID[0]), str(ingredId[0]), str(k[1]))

            return redirect(url_for("recipes.oppskrifter"))


        else:
            flash("Retten er allerede registrert", "warning")

    return render_template('legg-til-rett.html', form=form, ingredients=group_ingredients)

backend/reports/__init__.py
from backend.reports.views import reports

backend/reports/views.py
import pandas as pd
from flask import Blueprint, render_template, session, request
from flask_login import login_required

from backend.reports.queries import *
from flask_alchemy_db_creation.local_db_create import engine

reports = Blueprint('reports', __name__, template_folder='templates')


def test():
    pd.set_option('display.max_columns', None)
    pd.set_option('display.expand_frame_repr', False)

    res2 = pd.read_sql(ingredients_used_per_week_total(1,1).statement, engine)
    print(res2[['Ukemeny', 'Gruppe', 'Ingrediens', 'SumMengde', 'Enhet', 'SumBelop']])

    print("")
    print("")

    res = pd.read_sql(ingredients_used_per_week_per_dish(1,1,1).statement, engine)
    print(res[['Ukemeny', 'Gruppe', 'Oppskrift', 'Ingrediens', 'Mengde', 'Prognose', 'SumMengde', 'Enhet']])

    print("")
    print("")

    res3 = pd.read_sql(fetch_weekly_menus_for_group(3).statement, engine)
    print(res3)

    print("### MOST USED DISHES ###")
    res4 = pd.read_sql(recipes_most_used(1).statement, engine)
    print(res4[['name', 'SumRetter']])


if __name__ == '__main__':
    test()

@reports.route('/rapporter')
@login_required
def reports_base():

    return render_template('report_base.html')


@reports.route('/rapporter/oppskrifter')
@login_required
def most_used_dishes():
    groupId = session.get('group_to_use')

    recipes = recipes_most_used(groupId)

    return render_template('report_recipes.html', recipes=recipes)


@reports.route('/rapporter/ingredienser', methods=['GET', 'POST'])
@login_required
def ingredients_used_per_week():
    groupId = session.get('group_to_use')
    menuId = session.get('menuId')

    if 'menu' in request.args:
        session['menuId'] = request.args["menu"]
        menuId = session.get('menuId')

    totalcost = 0
    recipes = []
    perRecipe = False

    menus = fetch_weekly_menus_for_group(groupId)

    # If recipe specification
    if 'recipe' in request.args:
        recipeId = request.args["recipe"]
        res = ingredients_used_per_week_per_dish(menuId, recipeId, groupId)
        perRecipe = True

    # Else if menu selected
    elif 'menu' in request.args:
        res = ingredients_used_per_week_total(menuId, groupId)

    else:
        res = ingredients_used_per_week_total(0, groupId)

    if 'weeknum' in request.args:
        recipes = fetch_recipes_in_weekly_menu(menuId)
        for i in res:
            totalcost += i.SumBelop

    return render_template('report_ingredients.html', report=res, menus=menus, recipes=recipes, totalcost=totalcost,
                           perRecipe=perRecipe)

backend/weekly_menu/views.py
import string

import flask
from flask import Blueprint, flash, redirect, render_template, request, url_for, session
import backend.weekly_menu.queries as menu_queries
from backend.weekly_menu.forms import RegisterWeeklymenuForm, WeeklyMenuSelector, WeeklyMenuToDateForm, \
    WeeklyMenuWeekSelector

weeklyMenu = Blueprint('weeklyMenu', __name__, template_folder='templates')


@weeklyMenu.route('/ukesmeny', methods=['POST', 'GET'])
def ukesmeny():
    if menu_queries.check_first_weeklymenu_where_groupId(session.get('group_to_use')) != None:
        # Basic data collection
        weeklymenu_to_date_form = WeeklyMenuToDateForm(request.form)
        group_id = flask.session.get('group_to_use', 'not set')
        weekly_menus = menu_queries.fetch_all_weeklymenu_where_groupId(session['group_to_use'])
        weekly_menus_with_date = menu_queries.fetch_menus_with_dates_by_group_id(group_id)

        for i in weekly_menus:
            print(i.idWeeklyMenu)

        # hent ut i liste alle recepies i den gitte ukesmenyen.  hardkod ukesmenyen først.
        group_recipes = menu_queries.fetch_recipes_where_usergroupid(flask.session.get('group_to_use'))

        weeklyMenuRecepies = menu_queries.fetch_weeklymenu_recipes_where_name_usergroupid(flask.session.get('menuID'))
        activeMenu = menu_queries.fetch_weeklymenu_where_usergroupid(flask.session.get('group_to_use'))
        dishes = [i.name for i in weeklyMenuRecepies]

        form = RegisterWeeklymenuForm(request.form)
        formSelector = WeeklyMenuSelector(request.form)
        choice = []

        for i in weekly_menus:
            choice.append((i.idWeeklyMenu, i.name))
        for i in choice:
            if i[0] == int(flask.session.get('menuID')):
                choice.remove(i)
                choice.insert(0, i)

        formSelector.weeklyIdName.choices = choice

        if request.method == 'POST':
            # HENT DATA FRA MENY UKE-FORM
            if formSelector.weeklyIdName.data is not None:
                session['menuID'] = formSelector.weeklyIdName.data
                formSelector.weeklyIdName.data = session['menuID']
                return redirect(request.referrer)

            # HENT DATA FRA KNYTT-TIL-UKE-FORM
            if weeklymenu_to_date_form.week.data is not None and weeklymenu_to_date_form.year is not None:
                week = weeklymenu_to_date_form.week.data
                year = weeklymenu_to_date_form.year.data
                menu_queries.insert_to_weekly_menu_date(session['menuID'], year, week)
                flash(f"Meny knyttet til uke {week}!", "success")
                return redirect(request.referrer)

            if form.weekly_name.data is not None:
                weeklymanu_name = form.weekly_name.data
                weeklymenu_desc = form.weekly_desc.data

                # Do group already have menu with same name?
                if not menu_queries.fetch_weeklymenu_where_name_and_usergroupid(group_id, weeklymanu_name):

                    menu_queries.insert_to_weeklymenu(weeklymanu_name, weeklymenu_desc, group_id)

                    flash("Meny lagt til!", "success")
                    return redirect(url_for("weeklyMenu.ukesmeny"))
                else:
                    flash("Dere har allerede en meny med dette navnet", "warning")

        weeklyMenuRecepies = menu_queries.fetch_weeklymenu_recipes_where_name_usergroupid(flask.session.get('menuID'))
        weeklyMenus = menu_queries.fetch_menus_with_dates_by_group_id(group_id)
        selectedMenuName = menu_queries.fetch_menu_name_where_menu_id(session['menuID'])

        return render_template('ukesmeny.html', selectedMenuName=selectedMenuName,
                               weeklymenu_to_date_form=weeklymenu_to_date_form, recipes=group_recipes,
                               weeklyMenusWithDate=weekly_menus_with_date,
                               weeklyMenuRecepies=weeklyMenuRecepies,
                               activeMenu=activeMenu,
                               dishes=dishes, form=form, formSelect=formSelector, menuID=flask.session.get('menuID'))
    else:
        return redirect('/legg_til_ukesmeny')


@weeklyMenu.route('/legg_til_ukesmeny', methods=['POST', 'GET'])
def legg_til_ukesmeny():
    form = RegisterWeeklymenuForm(request.form)

    if request.method == 'POST':
        weeklymanu_name = form.weekly_name.data
        weeklymenu_desc = form.weekly_desc.data

        # Do group already have menu with same name?
        if not menu_queries.fetch_weeklymenu_where_name_and_usergroupid(flask.session.get('group_to_use'),
                                                                        weeklymanu_name):

            menu_queries.insert_to_weeklymenu(weeklymanu_name, weeklymenu_desc, flask.session.get('group_to_use'))

            flash("Meny lagt til!", "success")
            return redirect(url_for("index"))
        else:
            flash("Dere har allerede en meny med dette navnet", "warning")

    return render_template('newWeeklyMenu.html', form=form)


@weeklyMenu.route('/weekly_menu/<array>/update', methods=["GET", "POST"])
def updateRecipeHasIngrediens(array: str):
    return redirect(url_for("recipes.oppskrifter"))


@weeklyMenu.route('/weekly_menu/<recipe_id>/<quantity>/add', methods=["GET", "POST"])
def addRecipeToWeeklyMenu(recipe_id: int, quantity: int):
    menuID = flask.session.get('menuID')
    menu_queries.insert_to_recipe_has_weeklymenu(menuID, recipe_id, quantity)
    return redirect('/ukesmeny')


@weeklyMenu.route('/weekly_menu/<recipe_id>/<menu_ID>/delete', methods=["GET", "POST"])
def RemoveRecipeFromWeeklyMenu(recipe_id: int, menu_ID: int):
    menu_queries.remove_from_RecipeHasWeeklyMenu(recipe_id, menu_ID)
    return redirect('/ukesmeny')


@weeklyMenu.route('/handleliste', methods=["GET", "POST"])
def handleliste():
    weekly_menu_w_dates = menu_queries.fetch_menus_with_dates_by_group_id(session['group_to_use'])

    formSelector = WeeklyMenuWeekSelector(request.form)
    weekly_menus_with_dates_choices = []
    form = RegisterWeeklymenuForm(request.form)

    for i in weekly_menu_w_dates:
        yearWeek = "År: " + str(i[1].year) + "              Uke: " + str(i[1].weekNumber)
        weekly_menus_with_dates_choices.append((i[0].idWeeklyMenu, yearWeek))
    for i in weekly_menus_with_dates_choices:
        if i[0] == int(flask.session.get('menuID')):
            weekly_menus_with_dates_choices.remove(i)
            weekly_menus_with_dates_choices.insert(0, i)

    formSelector.weeklyMenuWeekId.choices = weekly_menus_with_dates_choices

    if request.method == 'POST':
        if formSelector.weeklyMenuWeekId.data is not None:
            session['menuID'] = formSelector.weeklyMenuWeekId.data
            formSelector.weeklyMenuWeekId.data = session['menuID']

            return redirect(request.referrer)

    allIngredientsFromWeekly = menu_queries.get_all_ingredients_and_quantities_cost_etc_shopping_in_weeklymenu(
        session['menuID'], session['group_to_use'])
    totalsum = 0
    if allIngredientsFromWeekly == []:
        weekly_menu_name = "Det er ingen ukesmeny her fordi ingen er registrert på uke."
    else:
        weekly_menu_name = menu_queries.fetch_menu_name_where_menu_id(session['menuID'])

    for ingredient in allIngredientsFromWeekly:
        totalsum += ingredient[4]

    return render_template('handleliste.html', weekly_menu_name=weekly_menu_name, form=form, totalsum=totalsum,
                           ingredients=allIngredientsFromWeekly, formSelect=formSelector)


@weeklyMenu.route('/<ingrediens_id>/<quantity>/update', methods=["GET", "POST"])
def updateIngredient(ingrediens_id: str, quantity: str):
    group = flask.session.get('group_to_use')
    menu_queries.editIngredientShopping(group, ingrediens_id, quantity)
    return redirect('/handleliste')

templates/flash_messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        <div class="position-absolute bottom-0 end-0 alert-container">
        {% for category, message in messages %}
            <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
        </div>
    {% endif %}
{% endwith %}

templates/handleliste.html
{% extends 'base.html' %}
{% block title %}Handleliste{% endblock %}
{% block heading %}Handleliste{% endblock %}
{% block description %}Se produktene du må kjøpe inn basert på rettene som du har lagt i ukesmenyen:
    <h2>{{ weekly_menu_name }}</h2>

{% endblock %}

{% block content %}
    <form method="POST" action="{{ url_for('weeklyMenu.handleliste',formid=1) }}" class="row">
        {{ formSelect.csrf_token }}
        <div class="form-group w-25 p-3">{{ formSelect.weeklyMenuWeekId(class="form-select", onchange="submit()") }}</div>
    </form>

    <form method="post" class="row">
        <div class="table-responsive">
            <table class="table">
                <thead>
                <tr style="color:rgb(0,0,0);">
                    <th>Produkt</th>
                    <th class="justify-content-end">Enhet</th>
                    <th>Antall</th>
                    <th>Enhets Pris</th>
                    <th>Sum Pris</th>
                </tr>
                </thead>
                <tbody>
                {% for ingredient in ingredients %}
                    {% if ingredient[5] > 0 %}
                        <tr style="color:rgb(11,11,11);">
                            {#                            <td>#}
                            {#                                <div class="form-check"><input class="form-check-input" type="checkbox"#}
                            {#                                                               id="formCheck-1"><label class="form-check-label"#}
                            {#                                                                                       for="formCheck-1">{{ ingredient[1] }}</label>#}
                            {#                                </div>#}
                            {#                            </td>#}
                            <td>{{ ingredient[1] }}</td>
                            <td>{{ ingredient[3] }}</td>
                            <td>{{ ingredient[2] }}</td>
                            <td>{{ ingredient[5] }}</td>
                            <td>{{ ingredient[4] }}</td>
                            <td>
                                <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                                        data-bs-target="#modal{{ ingredient[1] }}">Kjøp
                                </button>
                            </td>

                        </tr>
                        <!-- Modal -->
                        <div class="modal fade" id="modal{{ ingredient[1] }}" tabindex="-1"
                             aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-lg">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">
                                            Rediger {{ ingredient.ingredientName }}</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body row align-items-end">

                                        <div class="form-group col">
                                            <label>Ingrediens</label>
                                            <input id="{{ loop.index }}-nameForm" class="form-control" type="text"
                                                   value="{{ ingredient[1] }}" disabled readonly>
                                        </div>

                                        <div class="form-group col">
                                            <label>Antall</label>
                                            <input id="{{ loop.index }}-quantityForm" type="number" min="0"
                                                   class="form-control" id="exampleFormControlInput1"
                                                   value="{{ ingredient[2] }}">
                                        </div>
                                        <div class="form-group col">
                                            <label>Enhet</label>
                                            <input id="{{ loop.index }}-unitForm" class="form-control" type="text"
                                                   value="{{ ingredient[3] }}" disabled readonly>
                                        </div>

                                    </div>
                                    <div class="modal-footer">

                                        <a href="#" id="{{ loop.index }}-myLink" type="button"
                                           class="btn btn-primary">Oppdater</a>

                                        <script>
                                            document.getElementById("{{ loop.index }}-myLink").onclick = function () {
                                                var getQuantity = document.getElementById('{{ loop.index }}-quantityForm').value;
                                                document.getElementById('{{ loop.index }}-myLink').href = '/{{ ingredient[0] }}/' + getQuantity + '/update';
                                            }
                                        </script>

                                    </div>

                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
        <h5 style="height:45px;color:rgb(3,3,3);font-family:'Source Sans Pro', sans-serif;margin-top:20px;">Totalt
            : {{ totalsum }} ,-</h5>
    </form>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block title %}Mainpage{% endblock %}
{% block heading %}Munchbase{% endblock %}
{% block description %}Din digitale matplanlegger :-){% endblock %}
{% block content %}
    {% include 'flash_messages.html' %}

    {% if  not current_user.is_authenticated %}
        <div class="container" style="max-width: 1000px;">

            <form method="POST" action="{{ url_for('auth.login') }}" class="row">

                <img class="mb-4" src="https://www.svgrepo.com/show/115503/burger.svg" alt="" width="72" height="57">
                <h1 class="h3 mb-3 fw-normal">Logg inn</h1>

                <div class="form-group p-3">
                    {{ form.username(class="form-control",placeholder="brukernavn") }}
                </div>
                <div class="form-group p-3">
                    {{ form.password(class="form-control",placeholder="passord") }}
                </div>
                <div class="form-floating">
                    {{ form.submit(class_="btn btn-success") }}
                </div>
            </form>
        </div>
    {% else %}
        <p>Velkommen {{ current_user.username }}</p>
    {% endif %}
{% endblock %}

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark p-3 mb-4">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-label="Toggle">
        <span class="navbar-toggler-icon"></span>
    </button>

    {% if current_user.is_authenticated %}
        <a class="navbar-brand" href="{{ url_for('index') }}">Munchbase {{ session.get('groupname_to_use') }}</a>
    {% else %}
        <a class="navbar-brand" href="{{ url_for('index') }}">Munchbase </a>
    {% endif %}
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul id="navigation" class="navbar-nav mr-auto">

            {% if current_user.is_authenticated and session.get('groupname_to_use') == "" %}
                <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.logout') }}">Logg ut</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.profil') }}">Min profil</a></li>
                <li class="nav-item"><a class="nav-link"
                                        href="{{ url_for('auth.groupadmin') }}">Gruppeadministrasjon</a></li>

            {% elif current_user.is_authenticated and session.get('groupname_to_use') !="" %}
                <li class="nav-item"><a class="nav-link" href="{{ url_for('recipes.oppskrifter') }}">Oppskrifter</a>
                </li>
                <li class="nav-item"><a class="nav-link" href="{{ url_for('ingredient.new') }}">Ingredienser</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ url_for('weeklyMenu.handleliste') }}">Handleliste</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ url_for('weeklyMenu.ukesmeny') }}">Ukesmeny</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ url_for('recipes.legg_til_rett') }}">Legg til rett</a>
                </li>
                <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.profil') }}">Min profil</a></li>
                <li class="nav-item"><a class="nav-link"
                                        href="{{ url_for('auth.groupadmin') }}">Gruppeadministrasjon</a></li>
                <li class="nav-item"><a class="nav-link"
                                        href="{{ url_for('reports.reports_base') }}">Rapporter</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.logout') }}">Logg ut</a></li>



            {% else %}
                <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.register') }}">Register</a></li>
            {% endif %}
        </ul>

    </div>
</nav>

templates/report.html
{% extends 'index.html' %}
{% block title %}Rapporter{% endblock %}
{% block heading %}Dine rapporter{% endblock %}
{% block content %}
<table class="table table-striped table-hover">
{% if menus[0] %}
<h4>Forbruk per ingrediens</h4>
<br>
<h6>Ukemenyer:</h6>
{% for menu in menus %}
    <span class="badge badge-secondary"><a href="{{ url_for('reports.ingredients_used_per_week', weeknum=menu[1].weekNumber, year=menu[1].year , menu=menu[0].idWeeklyMenu) }}">{{ menu[1].weekNumber }} - {{ menu[0].name }}</a></span>
{% endfor %}
<br>
<br>
{% if report[0] %}
<h6>Ukens oppskrifter:</h6>
{% for recipe in recipes %}
    <span class="badge badge-secondary"><a href="{{ url_for('reports.ingredients_used_per_week', weeknum=recipe[2].weekNumber, year=recipe[2].year, recipe=recipe[0].idRecipe) }}">{{ recipe[0].name }}</a></span>
{% endfor %}
<br>
<br>
<h3>{{ report[1].Ukemeny }} :
    {% if perRecipe %}
        {{ report[1].Oppskrift }}
    {% else %} Sum for uken
    {% endif %}
</h3>
    <thead>
    <tr>
        <th>Vare</th>
        <th>Forbruk</th>
        <th>Enhet</th>
        <th>Pris </th>
        <th>Kostnad</th>
    </tr>
    </thead>
    <tbody>
    {% for i in report %}
        <tr>
            <td>{{ i.Ingrediens }}</td>
            <td>{{ "{:,.2f}".format(i.SumMengde) }}</td>
            <td>{{ i.Enhet }}</td>
            <td>{{ "kr {:,.2f}".format(i.Pris)}}</td>
            <td>{{ "kr {:,.2f}".format(i.SumBelop) }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<h5>Total kostnad: {{ "kr {:,.2f}".format(totalcost) }} </h5>
    {% else %}
    <h2>Velg en ukemeny for å se rapporter</h2>
    {% endif %}
{% else %}
    <h2>Du har ingen ukesmenyer knyttet til en uke</h2>
{% endif %}
{% endblock %}

templates/report_ingredients.html
{% extends 'report_base.html' %}
{% block report %}
<table class="table table-striped table-hover">
{% if menus[0] %}
<br>
<h6>Ukemenyer:</h6>
<h5>
{% for menu in menus %}
    <span class="badge badge-light"><a href="{{ url_for('reports.ingredients_used_per_week', weeknum=menu[1].weekNumber, year=menu[1].year , menu=menu[0].idWeeklyMenu) }}">{{ menu[1].weekNumber }} - {{ menu[0].name }}</a></span>
{% endfor %}
</h5>
{% if report[0] %}
<h6>Ukens oppskrifter:</h6>
<h5>
{% for recipe in recipes %}
    <span class="badge badge-light"><a href="{{ url_for('reports.ingredients_used_per_week', weeknum=recipe[2].weekNumber, year=recipe[2].year, recipe=recipe[0].idRecipe) }}">{{ recipe[0].name }}</a></span>
{% endfor %}
</h5>
<br>
<h3>{{ report[1].Ukemeny }} :
    {% if perRecipe %}
        {{ report[1].Oppskrift }}
    {% else %} Sum for uken
    {% endif %}
</h3>
    <thead>
    <tr>
        <th>Vare</th>
        <th>Forbruk</th>
        <th>Enhet</th>
        <th>Pris </th>
        <th>Kostnad</th>
    </tr>
    </thead>
    <tbody>
    {% for i in report %}
        <tr>
            <td>{{ i.Ingrediens }}</td>
            <td>{{ "{:,.2f}".format(i.SumMengde) }}</td>
            <td>{{ i.Enhet }}</td>
            <td>{{ "kr {:,.2f}".format(i.Pris)}}</td>
            <td>{{ "kr {:,.2f}".format(i.SumBelop) }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<h5>Total kostnad: {{ "kr {:,.2f}".format(totalcost) }} </h5>
    {% else %}
    <br>
    <br>
    <h2>Velg en ukemeny for å se rapporter</h2>
    {% endif %}
{% else %}
    <h2>Du har ingen ukesmenyer knyttet til en uke</h2>
{% endif %}
{% endblock %}